services:
  - type: static
    name: anti-memo-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html